services:
  - type: web
    name: aa-auto-rebooker
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ASSISTANT_ID
        sync: false
      - key: SHARED_SECRET
        sync: false
